### ISSUE TITLE
Did you verify stats at step 9?

### ISSUE THREAD

**Issue by mickvanhulst** [lej-la/deep-ed-pytorch#3]
Hi,

Let me begin with thanking you for posting your PyTorch code, it's very helpful! At step 9 I would like to verify the stats of the generated files, but unfortunately, the stats that I get returned do not align with the stats mentioned in the code. Specifically, the stats for the file wned-msnbc and aida_testA do not match.

During the development of your code, did you perform these tests (could you verify if the stats are correct or not)?
If you did, any idea why my results are incorrect?

**Comment by lej-la** [comment]
Hi,

The stats may differ a bit, are your numbers completely different or is it just a small percentage?
I am, unfortunately, not able to check the stats now, as I don't have the generated data.

**Comment by mickvanhulst** [comment]
Hi,

They differ a bit, any idea what the cause of this may be and if this could also occur in the Lua implementation? I'm using this for my research and in terms of reproducibility knowing what causes the difference is of importance.

Thanks for your quick response!

**Comment by lej-la** [comment]
I have been using this for preprocessing the data, I've had a small difference in reproducing the results, but it was ok for my research.
In case you'd like the exact same preprocessing, you might want to run the original Lua code.
I might look into this and try to fix it, but it won't be sooner than September.
I think that the difference might be in some kind of parsing or regexp.

**Comment by mickvanhulst** [comment]
Hmm okay, thanks for the information. I suspect it has to do with the generation of p(e|m) as the files generated by the original Lua code are of a different size than the ones generated by the PyTorch code.

Thank you for your time and answers!

**Comment by lej-la** [comment]
You're welcome. Please feel free to ask more questions if needed.
